name: Make new release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  semver_labels:
    name: Read semver labels from merged PR
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      semver_app: ${{ steps.semver_labels.outputs.semver_app }}
      semver_chart: ${{ steps.semver_labels.outputs.semver_chart }}
      skip_release: ${{ steps.semver_labels.outputs.skip_release }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: ./.github/actions/check-pr-semver-labels
        id: semver_labels
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN}}
  semver_update:
    if: ${{needs.semver_labels.outputs.skip_release == 'False'}}
    name: Update semver for every eligible file of repo (helm charts, package.json , etc.)
    runs-on: ubuntu-latest
    needs: semver_labels
    environment: prod
    outputs:
      app_version: ${{ steps.get_new_ver.outputs.version }}
    steps:
      - name: Make Release
        id: release
        uses: pagopa/github-actions-template/node-release@473d7a78d28e15cab46dcaf766087e60604d6a40 # v1.13.3
        with:
          semver: ${{ needs.semver_labels.outputs.semver_app }}
          github_token: ${{ secrets.BOT_TOKEN_GITHUB }}
          skip_ci: true
          prerelease: false